# Generated by Django 2.2.5 on 2021-11-12 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_change_status', models.DateTimeField(verbose_name='Дата изменения')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.Task')),
                ('taskStatus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tables.TaskStatus')),
            ],
        ),
    ]
