# Generated by Django 2.2.5 on 2021-11-24 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0005_task_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktable',
            name='taskStatus',
        ),
        migrations.AddField(
            model_name='task',
            name='date_change_status',
            field=models.DateTimeField(null=True, blank=True, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Назначено', 'Назначено'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено'), ('Проверено', 'Проверено'), ('Закрыта', 'Закрыта')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tasktable',
            name='cooperator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='tasktable',
            name='task',
        ),
        migrations.AddField(
            model_name='tasktable',
            name='task',
            field=models.ManyToManyField(to='tables.Task'),
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
    ]
