# Generated by Django 2.2.5 on 2021-11-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0006_auto_20211124_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cooperator',
            name='user',
        ),
        migrations.AddField(
            model_name='cooperator',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cooperator',
            name='email',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cooperator',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cooperator',
            name='phone',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_change_status',
            field=models.DateTimeField(null=True, blank=True, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
    ]
