# Generated by Django 2.2.5 on 2021-11-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0010_auto_20211128_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date_change_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_finish_task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='task_status',
        ),
        migrations.AddField(
            model_name='tasktable',
            name='date_change_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktable',
            name='date_finish_task',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tasktable',
            name='task_status',
            field=models.CharField(choices=[('Назначено', 'Назначено'), ('В работе', 'В работе'), ('Выполнено', 'Выполнено'), ('Проверено', 'Проверено'), ('Закрыта', 'Закрыта')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='condition',
            field=models.TextField(),
        ),
    ]
