# Generated by Django 2.2.5 on 2021-12-05 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tables', '0011_auto_20211129_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='cooperator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.Specialist'),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='date_change_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='date_finish_task',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Cooperator',
        ),
    ]
