# Generated by Django 2.2.5 on 2021-12-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0012_auto_20211205_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialist',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='date_change_status',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата изменения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tasktable',
            name='date_finish_task',
            field=models.DateTimeField(blank=True, null=True),
            preserve_default=False,
        ),
    ]
