# Generated by Django 2.2.5 on 2021-12-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0013_auto_20211206_1333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_status', models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('In review', 'In review'), ('Done', 'Done')], max_length=200, null=True)),
                ('date_change_status', models.DateTimeField(verbose_name='Дата изменения')),
                ('date_finish_task', models.DateTimeField()),
                ('cooperator', models.ManyToManyField(to='tables.Specialist')),
            ],
        ),
        migrations.RenameField(
            model_name='task',
            old_name='condition',
            new_name='description',
        ),
        migrations.DeleteModel(
            name='TaskTable',
        ),
        migrations.AddField(
            model_name='projects',
            name='task',
            field=models.ManyToManyField(to='tables.Task'),
        ),
    ]
