# Generated by Django 2.2.5 on 2021-12-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0014_auto_20211208_1748'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='cooperator',
        ),
        migrations.AddField(
            model_name='task',
            name='specialist',
            field=models.ManyToManyField(to='tables.Specialist'),
        ),
    ]
