# Generated by Django 2.2.5 on 2021-12-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0015_auto_20211210_2054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='specialist',
        ),
        migrations.AddField(
            model_name='projects',
            name='specialist',
            field=models.ManyToManyField(to='tables.Specialist'),
        ),
    ]
