# Generated by Django 2.2.5 on 2021-12-10 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0016_auto_20211210_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='task_status',
            new_name='project_status',
        ),
        migrations.AddField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('To do', 'To do'), ('In progress', 'In progress'), ('In review', 'In review'), ('Done', 'Done')], max_length=200, null=True),
        ),
    ]
