# Generated by Django 2.2.5 on 2022-01-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0017_auto_20211210_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
