# Generated by Django 2.2.5 on 2022-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0019_auto_20220110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='data_created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
