# Generated by Django 2.2.5 on 2022-01-13 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0021_auto_20220110_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='task',
        ),
        migrations.AddField(
            model_name='projects',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tables.Task'),
        ),
    ]
