# Generated by Django 2.2.5 on 2022-01-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0022_auto_20220113_1313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='task',
        ),
        migrations.AddField(
            model_name='projects',
            name='task',
            field=models.ManyToManyField(to='tables.Task'),
        ),
    ]
